# Desired action specification
# string specifies the type of action

#######################
# Currently implimented
#######################
# 'change_depth'
# 'change_heading'
string actionID
# common specifications, may be ignored depending on message type
float64 target_depth
float64 target_heading

---

# Sucesseful result
string actionID
float64 end_depth
float64 end_heading

---

# feedback message
string actionID
float64 current_depth
float64 current_heading
